
data = """1	Exploring individual, cultural and structural components of health communication programs: A gender integrative approach	F-FPM-P	Pant, Saumya; Pathak-Shelat, Manisha; Sharma, Aanchal; Krishnatray, Pradeep	Health communication in the changing media landscape: perspectives from developing countries	Book Chapter	Edited Book	Book Chapter	ISBN: 9783319335391, pp 197-213	India	National	2016	2016-2017	N/A	N/A	N/A	Palgrave Macmillan	N/A	Pant, S., Pathak-Shelat, M., Sharma, A., & Krishanatray, P. (2016). Exploring individual, cultural and structural components of health communication programs: A gender integrative approach. In R.K. Vemula., & S.M. Gavaravarapu. (Eds.), Health communication in the changing media landscape: Perspectives from developing countries. (pp. 197-213). Cham: Palgrave Macmillan.	-	-	N/A	-	N/A	N/A	N/A	-	-
2	Social media: past, present and future	F-FPM-P	Chakravarty, Devpriya; Gaur, Shubhra; Khanna, Karman	Media: Past, Present and Future	Book Chapter	Edited Book	Chapter	ISBN: 9789386113443	India	National	2016	2016-2017	N/A	N/A	N/A	Shree Natraj Prakashan	N/A	Chakravarty, D., & Gaur, S. (2016). Social media: Past, present and future. In R. Ajwani., & U.K. Rai. (Eds.), Media: Past, present and future. (pp. 13-33). Delhi: Shree Natraj Prakshan.	-	-	N/A	-	N/A	N/A	N/A	-	-
3	People matters: A context of mergers and acquisitions	F-P	Bansal, Anjali	Proceedings of 5th Global Business and Finance Research Conference	Conference Paper	Conference Proceedings	Conference - Abstract Published	2-3 June 2016	Australia	International	2016	2016-2017	N/A	N/A	N/A	World Business Institute Australia	N/A	Bansal, A. (2016). People matters: A context of mergers and acquisitions. In Proceedings of 5th global business and finance research conference. Sydney: World Business Institute Australia.	-	-	N/A	-	N/A	N/A	N/A	-	-
4	Implications of unresolved soft-issues on employee commitment and satisfaction during post-merger integration	F-P	Bansal, Anjali	Conference of the International Journal of Arts & Sciences	Conference Paper	Conference Proceedings	Conference - Abstract Published	pp. 221		International	2016	2016-2017	N/A	N/A	N/A	Universitypublications.net	N/A	Bansal, A. (2016). Implications of unresolved soft-issues on employee commitment and satisfaction during post-merger integration. In Conference of the International journal of arts & sciences. (pp. 221).	-	-	N/A	-	N/A	N/A	N/A	-	-
5	For shoppers: It's about getting the best experience	F-ST-P	Mahasuar, Kiran; Deshmukh, Siddharth	Point-Of-Purchase	Magazine Article	Magazine	Article	Vol. 12, No. 06, 2017 pp 32-33	India	National	2017	2016-2017	N/A	N/A	N/A	Vasant Jante	N/A	Mahasuar, K., & Deshmukh, S. (2017, January). For shoppers: It's about getting the best experience. Point of purchase, 12(6), 32-33.	-	-	N/A	-	FT-50	N/A	N/A	-	-
6	Employer branding on attracting and retaining talent: Economic outlook	F-RA-P	Jhala, Moxda; Bhatia, Pooja; Panda, Rasananda	Services in emerging markets	Conference Paper	Conference Proceedings	Conference - Paper Published	2017 pp 225-234	India	National	2017	2016-2017	N/A	N/A	N/A	Excel India Publishers	N/A	Jhala, M., Bhatia, P., & Panda, R. (2017). Employer branding on attracting and retaining talent: economic outlook. In S. Parashar., J.P. Aagja., & T. Joshi (Eds.), Services in emerging markets. (pp. 225-234). New Delhi: Excel India Publishers.	-	-	N/A	-	N/A	N/A	N/A	-	-
7	Which is a better language of instruction in primary education: English or mother tongue?	F-RA-P	Chhetia, Kirtika; Vasavada-Oza, Falguni	Services in emerging markets	Conference Paper	Conference Proceedings	Conference - Paper Published	2017 pp 293-305	India	National	2017	2016-2017	N/A	N/A	N/A	Excel India Publishers	N/A	Chhetia, K., & Oza, F. (2017). Which is a better language of instruction in primary education: English or mother tongue?. In S. Parashar., J.P. Aagja., & T. Joshi (Eds.), Services in emerging markets (pp. 293-305). New Delhi: Excel India Publishers.	-	-	N/A	-	N/A	N/A	N/A	-	-
8	Usage of social media among housewives	RA-P	Gadhiya, Palak	Consumer behaviour & contemporary marketing strategy	Conference Paper	Conference Proceedings	Conference - Paper Published	2017 pp 191-196	India	National	2017	2016-2017	N/A	N/A	N/A	Excel India Publishers	N/A	Gadhiya, P. (2017). Usage of social media among housewives. In T. Joshi., J.P. Aagja., & S. Parashar (Eds.), Consumer behaviour & contemporary marketing strategy (pp. 191-196). New Delhi: Excel India Publishers.	-	-	N/A	-	N/A	N/A	N/A	-	-
9	Confluence for social change	RA-P	Mane, Rahul	Krushival	Newspaper Article	Newspaper	Article	22 January 2017	India	National	2017	2016-2017	N/A	N/A	N/A		N/A	Mane, R. (2017, January 22). Confluence for Social Change. Krushuval, http://www.krushival.in/Admin/raigadpaper/22Jan17/22%20page%209.jpg	-	-	N/A	-	N/A	N/A	N/A	-	-
10	The perspective, the proximate and the persistent: Economic survey 2016-2017	F-RA-P	Panda, Rasananda; Bhatia, Pooja	http://orissadiary.com	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	Orissa Diary	N/A	Panda R., & Bhatia, P. (2017, February 1). The perspective, the proximate and the persistent: Economic survey 2016-2017. http://orissadiary.com/ShowBussinessNews.asp?id=72054	-	-	N/A	-	N/A	N/A	N/A	-	-
11	Measuring ad-evoked nostalgia in India: An emerging market perspective-an abstract	F-P	Jain, Varsha	Creating marketing magic and innovative future marketing trends: Proceedings of the 2016 academy of marketing science (AMS) annual conference	Conference Paper	Conference Proceedings	Conference - Paper Published			International	2017	2016-2017	N/A	N/A	N/A	Springer	N/A	Jain, V., Merchant, A., Roy, S., & Ford, J.B., (2017). Measuring ad-evoked nostalgia in India: An emerging market perspective-an abstract. In M. Stieler (Ed.), Creating marketing magic and innovative future marketing trends: Proceedings of the 2016 academy of marketing science (AMS) annual conference (pp.1199-1199). Cham-Switzerland: Springer.	-	-	N/A	-	N/A	N/A	N/A	-	-
12	Structured abstract: Comprehending political branding and brand image of the BJP in India	F-FPM-P	Jain, Varsha: Ganesh B. E.	Creating marketing magic and innovative future marketing trends: Proceedings of the 2016 academy of marketing science (AMS) annual conference	Conference Paper	Conference Proceedings	Conference - Paper Published		Switzerland	International	2017	2016-2017	N/A	N/A	N/A	Springer	N/A	Jain, V., Pich, C., Ganesh, B.E., & Armannsdottir, G. (2017). Structured abstract: Comprehending political branding and brand image of the BJP in India. In M. Stieler (Ed.), Creating marketing magic and innovative future marketing trends: Proceedings of the 2016 academy of marketing science (AMS) annual conference (pp.1307-1313). Cham-Switzerland: Springer.	-	-	N/A	-	N/A	N/A	N/A	-	-
13	Structured abstract: Discovering relationships between Indian luxury brands and Indian consumers	F-P	Jain, Varsha	Creating marketing magic and innovative future marketing trends: Proceedings of the 2016 academy of marketing science (AMS) annual conference	Conference Paper	Conference Proceedings	Conference - Paper Published			International	2017	2016-2017	N/A	N/A	N/A	Springer	N/A	Jain, V., & Don, S. (2017). Structured abstract: Discovering relationships between Indian luxury brands and Indian consumers. In Stieler, M. (Ed.), Creating marketing magic and innovative future marketing trends: Proceedings of the 2016 academy of marketing science (AMS) annual conference (pp.1093-1099). Cham-Switzerland: Springer.	-	-	N/A	-	N/A	N/A	N/A	-	-
14	Union budget 2017-18: Much ado about nothing	F-P	Panda, Rasananda	http://www.thedialogue.co/	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	The Dialogue	N/A	Panda R., & Panda, P. (2017, February 5). Union budget 2017-18: Much ado about nothing. http://www.thedialogue.co/union-budget-2017-18-much-ado-about-nothing/	-	-	N/A	-	N/A	N/A	N/A	-	-
15	Managing the infovore consumer: Framework for digital point of sale	F-ST-P	Mahasuar, Kiran; Deshmukh, Siddharth	Point-Of-Purchase	Magazine Article	Magazine	Article	Vol. 12, No. 07, 2017 pp 36-38	India	National	2017	2016-2017	N/A	N/A	N/A	Vasant Jante	N/A	Mahasuar, K., & Deshmukh, S. (2017, February). Managing the infovore consumer: Framework for digital point of sale. Point of purchase, 12(7), 36-38.	-	-	N/A	-	N/A	N/A	N/A	-	-
Action moves to mint street this week	F-P	Panda, Rasananda	http://bizodisha.com	Internet Source	Internet Source	Article	2017, February 07	India	National	2017	2016-2017	N/A	N/A	N/A	Bizodisha	N/A	Panda, R., & Panda, P. (2017, February 7). Action moves to mint street this week. http://bizodisha.com/2017/02/action-moves-to-mint-street-this-week/	-	-	N/A	-	N/A	N/A	N/A	-	-
17	North block proposes mint street disposes	F-P	Panda, Rasananda	http://orissadiary.com	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	Orissa Diary	N/A	Panda R. (2017, February 8). North block proposes mint street disposes. http://orissadiary.com/ShowOriyaColumn.asp?id=72178	-	-	N/A	-	N/A	N/A	N/A	-	-
18	From the political theater of absurd in Chennai	F-P	Panda, Rasananda	http://www.thedialogue.co/	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	The Dialogue	N/A	Panda, R., & Panda, P. (2017, February 9). From the political theater of absurd in Chennai. http://www.thedialogue.co/from-the-political-theatre-of-absurd-in-chennai/	-	-	N/A	-	N/A	N/A	N/A	-	-
19	Women safety in India: An epitome or epitaph?	ST-P	Mahasuar, Kiran	http://www.thedialogue.co/	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	The Dialogue	N/A	Mahasuar, K. (2017, February 15). Women safety in India: An epitome or epitaph? http://www.thedialogue.co/3541-2/	-	-	N/A	-	N/A	N/A	N/A	-	-
20	Women entrepreneurship: A behavioural economics approach	F-RA-P	Bhatia, Pooja; Panda, Rasananda	Twelfth biennial conference on entrepreneurship: conference papers - Vol.2	Conference Paper	Conference Proceedings	Conference -Paper Published	Vol. 02,  PP. 1367-1377	India	National	2017	2016-2017	N/A	N/A	N/A	Entrepreneurship Development Institute of India (EDI), Gandhinagar and Bookwell	N/A	Bhatia, P., & Panda, R. (2017). Women entrepreneurship: A behavioural economics approach. In S. Misra., S. Shukla., &  G. Batthini (Eds.), Twelfth biennial conference on entrepreneurship: conference papers Vol.2 (pp.1367-1373). Gandhinagar: Entrepreneurship Development Institute of India (EDI) and Bookwell.	-	-	N/A	-	N/A	N/A	N/A	-	-
21	Odisha budget 2017-18: Sub-fedealism at state lavel is the need	F-P	Panda, Rasananda	http://orissadiary.com	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	Orissa Diary	N/A	Panda, R. (2017, February 26). Odisha budget 2017-18: Sub-fedealism at state lavel is the need. http://www.orissadiary.com/CurrentNews.asp?id=72468	-	-	N/A	-	N/A	N/A	N/A	-	-
22	Authentic leadership in a VUCA world and role of micro-agression	F-RA-P	Panda, Rasananda; Karani, Anushree	Researchers World: Journal of Arts, Science and Commerce	Journal Paper	Journal	Paper	Vol. VIII, No.1, 2017 pp 119-124	India	National	2017	2016-2017	N/A	Global Impact Factor (GIF) - 0.685	N/A	ERM Publications	N/A	Panda, R., & Karani A. (2017). Authentic leadership in a VUCA world and role of micro-agression. Researchers World: Journal of Arts, Science and Commerce, 13(1), 119-124.	-	-	Global Impact Factor (GIF) - 0.685	-	N/A	N/A	4	-	-
23	Odisha budget 2017-18: Fiscal prudence amidst symbolism and tokenism	F-P	Panda, Rasananda	http://orissadiary.com	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	Orissa Diary	N/A	Panda, R. (2017, March 1). Odisha budget 2017-18: Fiscal prudence amidst symbolism and tokenism. http://orissadiary.com/CurrentNews.asp?id=72538	-	-	N/A	-	N/A	N/A	4*	-	-
24	India should now make up the opportunities is lost in partition	FPM-P	Biswas, Mitrajit	https://www.youthkiawaaz.com/	Internet Source	Internet Source	Article		India	National	2017	2016-2017	N/A	N/A	N/A	Youth ki awaaz	https://www.youthkiawaaz.com/2017/02/an-opportunity-missed-in-tears/	Biswas, M. (2017, February 7). India should now make up the opportunities is lost in partition. https://www.youthkiawaaz.com/2017/02/an-opportunity-missed-in-tears/	-	-	N/A	-	N/A	N/A	N/A	-	-
25	Devbhumi: Making a sweet buzz with organic honey in Uttarakhand	FPM-P	Rawat, Sandeep	Rural & Marketing	Magazine Article	Magazine	Article	Vol. 06, No. 03, 2017 pp 32-35	India	National	2017	2016-2017	N/A	N/A	N/A	i9 Media	N/A	Rawat, S. (2017 March). Devbhumi: Making a sweet buzz with organic honey in Uttarakhand. Rural & Marketing, 6(3), 32-35.	-	-	N/A	-	N/A	N/A	N/A	-	-
26	Uttar Pradesh poll verdicts: Warning bell for Odisha CM Naveen Patnaik	F-P	Panda, Rasananda	http://orissadiary.com	Internet Source	Internet Source	Article	2017: March 12	India	National	2017	2016-2017	N/A	N/A	N/A	Orissa Diary 	N/A	Panda, R. (2017, March 12). Uttar Pradesh poll verdicts: Warning bell for Odisha CM Naveen Patnaik. http://orissadiary.com/CurrentNews.asp?id=72703	-	-	N/A	-	N/A	N/A	N/A	-	-
27	Rediscovering Sarkhej: Narrating belonging in Ahmedabad	F-P	Thomas, Pooja	International Journal of Postcolonial Studies	Journal Paper	Journal	Paper	2017: March 10	USA	International	2017	2016-2017	N/A	0.13 (SJR)	N/A	Taylor and Francis Online	https://doi.org/10.1080/1369801X.2017.1294100	Thomas, P. (2017). Rediscovering Sarkhej: Narrating belonging in Ahmedabad. Interventions, 19(5), 706-723. DOI: https://doi.org/10.1080/1369801X.2017.1294100	-	-	0.13 (SJR)	-	N/A	N/A	N/A	-	-
28	Gratifications of Facebook: A literature review	RA-P	Gadekar, Rahul	Online Journal of Communication and Media Technologies	Journal Paper	Journal	Paper	Vol. 07, No. 01, 2017 pp 87-103	Cyprus	International	2017	2016-2017	N/A	N/A	N/A	Online Journal of Communication and Media Technologies	N/A	Gadekar, R., & Krishnatray, P. (2017). Gratifications of facebook: A literature review. Online Journal of Communication and Media Technologies, 7(1), 87-103.	-	-	N/A	-	N/A	N/A	N/A	-	-
29	New India, constitutional nicety and myriad role of governors	F-P	Panda, Rasananda	http://www.thedialogue.co/	Internet Source	Internet Source	Article	2017: March 14	India	National	2017	2016-2017	N/A	N/A	N/A	The Dialogue	N/A	Panda, R., & Panda, P. (2017, March 14). New India, constitutional nicety and myriad role of governors. http://www.thedialogue.co/new-india-constitutional-nicety-myriad-role-governors/	-	-	N/A	-	N/A	N/A	N/A	-	-
30	Sentiment analysis of virtual brand communities for effective tribal marketing	F-PGP-P	Pathak, Xema; Pathak-Shelat, Manisha	Journal of Research in Interacive Marketing	Journal Paper	Journal	Paper	Vol. 11, No. 01, 2017 pp 16-38	UK	International	2017	2016-2017	N/A	0.46 (SJR)	N/A	Emerald Publishing	N/A	Pathak, X., & Pathak-Shelat, M. (2017). Sentiment analysis of virtual brand communities for effective tribal marketing. Journal of Research in Interactive Marketing, 11(1), 16-38. http://dx.doi.org/10.1108/JRIM-09-2015-0069	-	-	0.46 (SJR)	-	N/A	N/A	3	-	-
31	Determining relationship between emotional intelligence and demographic variables	F-RA-P	Karani, Anushree; Panda, Rasananda	Asian Journal of Research in Social Sciences and Humanities	Journal Paper	Journal	Paper	Vol. 07, No. 02, 2017 pp 908-918	India	National	2017	2016-2017	Peer Reviewed	4.557 (SJIF)	N/A	Asian Research Consortium	N/A	Karani, A., Rajput, H., & Panda, R. (2017). Determining relationship between emotional intelligence and demographic variables. Asian Journal of Research in Social Sciences and Humanities, 7(2), 908-918. 	-	-	4.557 (SJIF)	-	N/A	N/A	N/A	-	-
32	Juxtaposition of the liberalisation policies and the competition laws in India	F-RA-P	Biswas, Shreya; Panda, Rasananda	Law and Economics: Breaking new grounds	Book Chapter	Edited Book	Chapter	2017 pp 257-274	India	National	2017	2016-2017	N/A	N/A	N/A	Eastern Book Company	N/A	Biswas, S., & Panda, R. (2017). Juxtaposition of the liberalisation policies and the competition laws in India. In R. Nagar., P.M. Prasad., & P. Mamidi (Eds.), Law and Economics: Breaking new grounds. (pp.257-274). Lucknow: Eastern Book Company.	-	-	N/A	-	N/A	N/A	N/A	-	-
33	A revelation of employee feelings of alienation during post-mergers and acquisition: An outcome of perceived organizational justice	F-P	Bansal, Anjali	Emerald Insight	Journal Paper	Journal	Paper	2017 March	UK	International	2017	2016-2017	Peer Reviewed	0.38 (SJR)	N/A	Emerald Publishing	N/A	Bansal, A. (2017). A revelation of employee feelings of alienation during post-mergers and acquisition: An outcome of perceived organizational justice. Journal of Organizational Change Management, 30(3), 417-439.	-	-	0.38 (SJR)	-	N/A	N/A	2	-	-
34	Demystifying the UP elections verdict: A common man’s perspective	ST-P	Mahasuar, Kiran	http://www.thedialogue.co/	Internet Source	Internet Source	Article	2017: March 27	India	National	2017	2016-2017	N/A	N/A	N/A	The Dialogue	N/A	Mahasuar, K. (2017, March 24). Demystifying the UP elections verdict: A common man’s perspective. http://www.thedialogue.co/3940-2/	-	-	N/A	-	N/A	B	N/A	Q1	-
35	Understanding the role of media education in promoting religious literacy A critical pedagogy for primary school students in rural India	FPM-P	Bhatia, Kiran	Media Education Research Journal	Journal Paper	Journal	Paper	Vol. 07, No. 02, 2017 pp 11-28	India	National	2017	2016-2017	N/A	Peer Reviewed	`	Auteur Publishing	N/A	Bhatia, K. (2017). Understanding the role of media education in promoting religious literacy: A critical pedagogy for primary school students in rural India. Media Education Research Journal, 7(2), 11-28.	-	-	Peer Reviewed	-	N/A	N/A	N/A	-	-
36	Understanding the politics of gendered identities in India	FPM-P	Bhatia, Kiran	WSRC Communique	Newsletter Article	Newsletter	Article	2017: January, No. 01, pp 35-36	India	National	2017	2016-2017	N/A	N/A	N/A	WSRC - The Maharaja Sayajirao University of Baroda	N/A	Bhatia, K. (2017 January). Understanding the politics of gendered identities in India. WSRC Communique, (1), 35-36.	-	-	N/A	-	N/A	N/A	N/A	-	-
37	Surrogacy law in India To be or not to be - Is that	RA-P	Mane, Rahul	WSRC Communique	Newsletter Article	Newsletter	Article	2017: January, No. 01, pp 49-54	India	National	2017	2016-2017	N/A	N/A	N/A	WSRC - The Maharaja Sayajirao University of Baroda	N/A	Mane, R. (2017 January). Surrogacy law in India: To be or not to be - Is that the question here?. WSRC Communique, (1), 49-54.	-	-	N/A	-	N/A	N/A	N/A	-	-
38	Reading popular music festivals through the lens of Public sphere	FPM-P	Chakravarty, Devpriya	Jurnal Komunikasi: Malaysian Journal of Communication	Journal Paper	Journal	Paper	Vol. 07, No. 02, 2017 pp 11-28		International	2017	2016-2017	N/A	N/A	N/A	Universiti Kebangsaan Malaysia: The National University of Malaysia	N/A	Chakravarty, D. (2017). Reading popular music festivals through the lens of Public sphere. Jurnal Komunikasi: Malaysian Journal of Communication, 33(1), 32-42. Retrieved from: http://ejournal.ukm.my/mjc/article/view/17167	-	-	N/A	-	N/A	N/A	N/A	-	-
39	Persuasive rhetoric of rap: Relevance in the Indian context	FPM-P	Chakravarty, Devpriya	Media Watch	Journal Paper	Journal	Paper	Vol. 08, No. 01, 2017 pp 19-29	India	National	2017	2016-2017	N/A	N/A	N/A	Deepak Ranjan Jena	N/A	Chakravarty, D. (2017). Persuasive rhetoric of rap: Media Watch, 8(1). 19-29.	-	-	N/A	-	N/A	A*	N/A	Q2	-
40	Exploring meaning transfer in celebrity endorsements: Measurement and validation	F-P	Jain, Varsha	Asia-Pacific Journal of Business Administration	Journal Paper	Journal (Online)	Paper	Vol. 09, No. 02, p. 87-104	UK	International	2017	2017-2018	Peer Reviewed	N/A	N/A	Emerald Publishing	https://doi.org/10.1108/APJBA-06-2016-0058	Roy, S., & Jain, V. (2017). Exploring meaning transfer in celebrity endorsements: Measurement and validation. Asia-Pacific Journal of Business Administration, 9(2). 87-104 DOI: https://doi.org/10.1108/APJBA-06-2016-0058	-	-	N/A	-	N/A	N/A	N/A	-	-
41	Value network in heritage walks: Case studies of Ahmedabad city walks	F-P	Basalingappa, Anita; Sinha, Piyush	Journal of Heritage Management	Journal Paper	Journal (Online)	Paper	Vol. 01, No. 02, p. 191-204	India	National	2017	2017-2018	Peer Reviewed	N/A	N/A	SAGE	https://doi.org/10.1177/2455929616687897	Saiyed, A.A., Basalingappa, A., & Sinha, P. K. (2017). Value network in heritage walks: Case studies of Ahmedabad city walks. Journal of Heritage Management, 1(2). 191-204. DOI: https://doi.org/10.1177/2455929616687897	-	-	N/A	-	N/A	N/A	N/A	-	-
87	The role of the media in the construction of reality: politics of inclusion and exclusion	FPM-P	Bhatia, Kiran; Chakravarty, Devpriya; Khanna, Karman	Media, the state, and marginalization: Tackling challenges edited by Rachna Sharma	Book Chapter	Book	Chapter	2018: P. 48-61	UK	International	2018	2018-2019	N/A	N/A	N/A	Cambridge Scholars Publishing	N/A	Bhatia, K., Chakravarty, D., & Khanna, K. (2018). The role of the media in the construction of reality: Politics of inclusion and exclusion. In R. Sharma (Ed.) Media, the state, and marginalization: Tackling challenges. (pp. 49-61). Newcastle, UK: Cambridge Scholars Publishing.	-	-	N/A	-	-	-	-	-	-
88	Understanding relationships between customers and rural retail outlets	F-P	Basalingappa, Anita	Journal of Economics and Public Policy	Journal Paper	Journal	Paper	Vol. 03, No. 01	India	National	2018	2018-2019	Peer Reviewed	N/A	N/A	NMIMS University	N/A	Basalingappa, A., & Subhas, M.S. (2018). Understanding relationships between customers and rural retail outlets. Journal of Economics and Public Policy, 3(1), 9-18.	-	-	N/A	-	FT-50	A	-	Q1	-
89	Management of Fraud: Case of an Indian Insurance Company	F-P	Mall, Sunita	Accounting and Finance Research	Journal Paper	Journal	Paper	Vol. 07, No. 03	Canada	International	2018	2018-2019	Double-Blind Peer-Reviewed	N/A	C	Sciedu Press	https://doi.org/10.5430/afr.v7n3p18	Mall, S., Ghosh, P., & Shah P. (2018). Management of Fraud: Case of an Indian Insurance Company. Accounting and Finance Research, 7(3), 18-28. DOI: https://doi.org/10.5430/afr.v7n3p18	-	-	N/A	-	-	C	-	-	-
90	Contribution of insurance on economic growth in India: An econometric approach	F-P	Mall, Sunita	Journal of Applied Business and Economics	Journal Paper	Journal	Paper	Vol. 20, No. 01, p. 85-92 	USA	International	2018	2018-2019	Double-Blind Peer-Reviewed	N/A	C	North American Business Press	N/A	Mall, S. (2018). Contribution of insurance on economic growth in India: An econometric approach. Journal of Applied Business and Economics, 20(1), 85-92.	-	-	N/A	-	-	C	-	-	-
91	In which I am sung to, cry, and other suchlike: Reflections on research in and with Tibetan refugees in India	F-P	Siganporia, Harmony	Questions of culture in autoethnography edited by Phiona Stanley and Greg Vass	Book Chapter	Book	Chapter	ISBN: 9781351714242	USA	International	2018	2018-2019	N/A	N/A	N/A	Taylor and Francis Online	N/A	Siganporia, H. (2018). In which I am sung to, cry, and other suchlike: Reflections on research in and with Tibetan refugees in India. In P. Stanley., & G. Vass (Eds.) Questions of culture in autoethnography. (pp. 134-144). New York, USA: Routledge.	-	-	N/A	-	-	-	-	-	-
92	Stock returns and inflation: a tale of two periods in India	F-P	Bhanja, Niyati	Economic change and restructuring	Journal Paper	Journal	Paper	Vol. 51	USA	International	2018	2018-2019	Peer Reviewed	0.53 (SJR)	B	Springer International Publishing	https://doi.org/10.1007/s10644-018-9231-z	Bhanja, N., & Dar, A.B. (2018). Stock returns and inflation: A tale of two periods in India. Economic Change and Restructuring, 51, 413–438. DOI: https://doi.org/10.1007/s10644-018-9231-z	-	-	0.53 (SJR)	-	-	B	-	-	-
93	Scoring the city	F-P	Siganporia, Harmony	Seminar	Journal Paper	Journal	Paper	No. 707	India	National	2018	2018-2019	Peer Reviewed	N/A	N/A	Malvika Singh on behalf of Romeshraj Trust	N/A	Siganporia, H. (2018). Scoring the city. Seminar (707), 41-44.	-	-	N/A	-	-	N/A	4*	Q1	-
94	The warp and weft of Ahmedabad: Interviews with Mirali Chatterjee, Director of Social Security SEWA, Ahmedabad and Jayshree Lalbhai, Educationist and Trustee, NLRDF, Ahmedabad	F-P	Siganporia, Harmony	Seminar	Journal Paper	Journal	Paper	No. 707	India	National	2018	2018-2019	Peer Reviewed	N/A	N/A	Malvika Singh on behalf of Romeshraj Trust	N/A	Siganporia, H. (2018). The warp and weft of Ahmedabad: Interviews with Mirali Chatterjee, director of social security SEWA, Ahmedabad and Jayshree Lalbhai, educationist and trustee, NLRDF, Ahmedabad. Seminar, (707), 61-63.	-	-	N/A	-	-	N/A	4	-	-
95	Measuring the comparative efficacy of an attractive celebrity influencer vis-à-vis an expert influencer – a fashion industry perspective	F-P	Trivedi, Jay	International Journal of Electronic Customer Relationship Management	Journal Paper	Journal	Paper	Vol. 11 No. 03, p. 256-271	UK	International	2018	2018-2019	Peer Reviewed	SJR: 0.15	C	Inder Science Publishers	N/A	Trivedi, J. (2018). Measuring the comparative efficacy of an attractive celebrity influencer vis-à-vis an expert influencer: A fashion industry perspective. International Journal of Electronic Customer Relationship Management, 11(3), 256-271.	-	-	SJR: 0.15	-	-	C	-	-	-
96	I am the widow: an intellectual biography of Behramji Malabari	F-P	Siganporia, Harmony	Orient BlackSwan	Book	Book	Book	pp. xxi, 280 (ISBN: 978-93-5287-390-6)	India	National	2018	2018-2019	N/A	N/A	N/A	Orient BlackSwan	N/A	Siganporia, H. (2018). I am the widow: An intellectual biography of Behramji Malabari. Hyderabad: Orient BlackSwan.	-	-	N/A	-	-	-	-	Q4	-
97	Participatory communication developing alternative epistemes for emancipation	FPM-P	Bhatia, Kiran	Asian Journal of Applied Communication	Journal Paper	Journal	Paper	Vol. 7 No. 01	Malaysia	International	2018	2018-2019	N/A	N/A	N/A	University of Putra, Malaysia	N/A	Bhatia, K. (2018). Participatory communication developing alternative epistemes for emancipation. Asian Jornal of Applied Communication, 7(1), 1-10.	-	-	N/A	-	-	N/A	3	-	-
98	Business opportunity identification, investors and marketing sources for start-ups in India	F-P	Yagnik, Shailesh R.	Startup India and role of Libraries	Conference Paper	Conference Proceedings	Conference - Paper Published	pp. 49-53 (ISBN: 978-81-937673-1-3)	India	National	2018	2018-2019	N/A	N/A	N/A	ADINET Publishing	N/A	Yagnik, S.R. (2018). Business opportunity identification, investors and marketing sources for start-ups in India. In R. Bharucha., & S. Majumudar (Eds.) Startup India and role of Libraries (pp. 49-53). Ahmedabad: Ahmedabad Library Network.	-	-	N/A	-	-	N/A	-	-	-
99	Interaction between parents and children during food shopping	F-RA-P	Patel, Cherry; Kini, Shashank; Mathur, Mini	Journal of Emerging Technologies and Innovative Research	Journal Paper	Journal	Paper	Vo. 05, No. 08, pp.07-12	India	National	2018	2018-2019	Peer Reviewed	N/A	N/A	JETIR	N/A	Patel, C., Kini, S., & Mathur, M.(2018). Interaction between parents and children during food shopping. Journal of Emerging Technologies and Innovative Research, 5(8), 07-12. Retrieved from: http://www.jetir.org/papers/JETIRD006002.pdf	-	-	N/A	-	-	N/A	-	-	-
100	Marketing, communication, and democracy: Towards a dialogue between the disciplines of marketing and communication	F-P	Basalingappa, Anita; Kumar, Keval	The Marketing Review	Journal Paper	Journal	Paper	Vol. 18, No. 02, pp.149-160	UK	International	2018	2018-2019	N/A	N/A	C	Westburn Publishers Ltd	https://doi.org/10.1362/146934718X15333820910156	Basalingappa, A., & Kumar, K. (2018). Marketing, communication, and democracy: Towards a dialogue between the disciplines of marketing and communication. The Marketing Review, 18(2), 149-160. DOI:  https://doi.org/10.1362/146934718X15333820910156	-	-	N/A	-	-	C	-	-	-
109	Understanding Bi-directional media consumption in online shopping: A case of three cities in India	F-FPM-P	Jain, Varsha; Ganesh B. E.; Bansal, Amrita	Journal of Business and Management	Journal Paper	Journal	Paper	Vol. 24, No. 02, p. 47-74	China	International	2018	2018-2019	Peer Reviewed	N/A	C	Chapman University	N/A	Jain, V., Ganesh, B.E., Boaz, A., & Bansal, A. (2018). Understanding Bi-directional media consumption in online shopping: A case of three cities in India, Journal of Business and Management, 24(2), 47-74. Retrieved from: http://jbm.johogo.com/pdf/volume/2402/JBM-2402-03-full.pdf	-	-	N/A	-	-	C	-	-	-
154	Innovations in the sphere of ventilators: Arsenal to fight COVID-19	RA-P	Gupta, Soniya	International Journal of Scientific Research and Engineering Trends	Journal Paper	Journal	Paper	Online: p.1047-1051	India	National	2020	2020-2021	Peer-Reviewed	2.504 (Publication Impact Factor)	N/A	International Journal of Scientific Research and Engineering Trends	https://ijsret.com/wp-content/uploads/2020/05/IJSRET_V6_issue2_324.pdf	Gupta, S. (2020). Innovations in the sphere of ventilators: Arsenal to fight COVID-19. International Journal of Scientific Research and Engineering Trends, 6(2), 1047-1051. Retrieved from: https://ijsret.com/wp-content/uploads/2020/05/IJSRET_V6_issue2_324.pdf	-	-	2.504 (Publication Impact Factor)	-	N/A	N/A	-	Q4	-"""

rows = []
for line in data.strip().split('\n'):
    parts = line.split('\t')
    if len(parts) >= 28:
        row = parts[:28]
        rows.append(row)

import json
# Save to a file in the workspace
with open('/Users/jeetpitale/Libaray/dashboard-web-app/parsed_data.json', 'w') as f:
    json.dump(rows, f)
